version: '3.8'

services:
  pi-mongo-db:
    container_name: mongo-db
    build: ./db/mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
    driver: local